### ISSUE TITLE
[🔥WIP🔥] Migrating to kubectl v1.12 new plugin model (BREAKING CHANGES), krew v0.2 release.

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/krew#33]
Context:

- Kubernetes 1.12 implements git-style plugins (executables prefixed `kubectl-*` placed in PATH).

- Krew does **not** support this model (predates it), but we saw this coming during the design phase.

- This change will still **break krew** heavily.

- Now that kubernetes 1.12.0-beta.1 release is available, we need to make krew work with the new kubectl plugin model.

## Plan

- [x] **Determine which krew version will fully support the "new plugin model": (v0.2)**
- [x] **Provide breaking change notices**
  - [x] Release a patch version for krew, adding a warning to every major cmd (#40)
  - [x] Update README about krew version being incompatible (#36)
- [x] **Plugin manifest updates**
  - [x] Add a field to `platforms[]` indicating which file(s) should be symlinked (#35)
    - [x] allow naming the symlink from plugin name e.g: mtail&rarr;kubectl-mtail) (#42)
  - ~(Possibly) Disable unknown field checking in manifest YAML (and validate in "audit" cmd) to allow graceful addition of this field (but I think breaking everyone in this case is ok due to low user count)~
  - [x] (Possibly) Error out for manifests in v1alpha1. (#72)
- [x] **Krew mechanics**
  - [x] Determine a binary symlink path (like `~/.krew/bin`) (#49)
  - [x] Modify installation/upgrade to take symlinks into account. (#42)
  - [x] Manually test upgrading krew.
  - ~~Detect kubectl version (refuse to run if <v1.12) (#41)~~
- [x] **Index updates**
  - [x] Backport and test all krew-index with the new bin path. (https://github.com/GoogleContainerTools/krew-index/pull/24)
- [x] **Documentation**
  - [x] Add note: "krew only works with kubectl-1.12 and above" (remove breaking change notice)
  - [x] Have users add krew symlink path to $PATH
    - [x] Update install script and user guide (show how to update PATH)
    - [x] Mention this in krew meta-plugin CAVEATS section (#114)
  - [x] Update developer guide with changes to kubectl-1.12 plugin model (#100)
  - [x] Update developer guide with changes to krew (bin dir, symlinks etc) (#62)
  - [x] Update user guide with nrew instructions (#93)
- Upstream issues
  - [x] kubectl-1.12 doesn't allow dashes in plugin names (forces user to invoke by separating words into args) https://github.com/kubernetes/kubectl/issues/540 not sure what we can do about this. #59
- Release
  - [x] Update krew README installation instructions
  - [x] Update krew, downgrade kubectl 1.12 warning to a notice.
  - [x] Update krew.yaml to add `linux/arm` platform (was in #48) (#80)
  - [x] Fix krew.yaml with new binary names introduced (was in #48) (#80)
  - [x] Locally test.
  - [x] Set up GCB triggers
  - [x] Uninstall Travis CI trigger (#95, #89)
  - [x] Tag release
  - [x] Test GCS URLs

I'm probably missing a few but will update the list above continuously.

cc: @lbb

**Comment by lbb** [comment]
I don't like the idea of having a platforms[] type:
IMHO it should be a single value; this can break future features as "aliasing". It's also nice to have a single plugin for each installation.

**Comment by lbb** [comment]
Note was added but not checked (under Krew mechanics)

**Comment by ahmetb** [comment]
![image](https://user-images.githubusercontent.com/159209/47044888-3c09ef00-d146-11e8-8fa6-6271cde16432.png)

**Comment by ahmetb** [comment]
Phew.
